build: script
shallow_clone: true
skip_tags: true

environment:
  TZ: Asia/Shanghai
  GO15VENDOREXPERIMENT: 1
  GO111MODULE: on

install:
- uname -a
- go version
- gcc --version

build_script:
- go mod tidy || true
- go build -v -ldflags="-s -w"

test_script:
- go vet ./...
- go test -v -cover ./...

stack:
- go 1.8
- go 1.13
- go 1.18

image:
- MacOS
- Ubuntu
- Visual Studio 2019

matrix:
  exclude:
  - image: MacOS
    stack: go 1.8
  - image: Visual Studio 2019
    stack: go 1.8

for:
- matrix:
    only:
    - image: MacOS
      stack: go 1.18
    - image: Ubuntu
      stack: go 1.18
  init:
  - gvm install go1.18

- matrix:
    only:
    - image: MacOS
  before_build:
  - sw_vers
  before_test:
  - sudo systemsetup -settimezone $TZ

- matrix:
    only:
    - image: MacOS
      stack: go 1.18
  test_script:
  - go test -covermode=count -coverprofile=coverage.txt ./...
  on_success:
  - curl -fsSL https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import --no-default-keyring --keyring trustedkeys.gpg
  - curl -fsSL --remote-name-all https://uploader.codecov.io/latest/macos/codecov{,.SHA256SUM{,.sig}}
  - gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
  - shasum -a 256 -c codecov.SHA256SUM
  - chmod +x codecov
  - ./codecov

- matrix:
    only:
    - image: Ubuntu
  clone_folder: '$HOME/go/src/github.com/arnie97/emu-log'
  before_build:
  - lsb_release -a
  - export GOPATH=$HOME/go
  - (export GOROOT=$HOME/.gvm/gos/go1.12.17; $GOROOT/bin/go mod vendor; unset GOROOT)

- matrix:
    only:
    - image: Visual Studio 2019
  clone_folder: 'c:\go\src\github.com\arnie97\emu-log'
  environment:
    GOPATH: 'c:\go'
    PATH: 'c:\msys64\mingw64\bin;c:\msys64\bin;%PATH%'
  before_build:
  - ver
  before_test:
  - tzutil /s "China Standard Time"
